### ISSUE TITLE
unable to preprocess sample json file into pt file

### ISSUE THREAD

**Issue by emoryjianghang** [nlpyang/PreSumm#12]
Hi Yang, Do you know how I can fix this problem? 

This is the command I use to reproduce the error:

```
python preprocess.py -mode format_to_bert \
-raw_path /root/PreSumm/json_data/ \
-save_path /root/PreSumm/sample_data/  \
-lower \
-n_cpus 1 \
-log_file /root/PreSumm/logs/preprocess.log
```

I got the following error when trying to convert the sample json file to pt file:

```
Traceback (most recent call last):
  File "preprocess.py", line 73, in <module>
    eval('data_builder.'+args.mode + '(args)')
  File "<string>", line 1, in <module>
  File "/root/PreSumm/src/prepro/data_builder.py", line 287, in format_to_bert
    for d in pool.imap(_format_to_bert, a_lst):
  File "/root/anaconda3/envs/xsum/lib/python3.6/site-packages/multiprocess/pool.py", line 735, in next
    raise value
KeyError: '[SEP]'
```

**Comment by nlpyang** [comment]
I cannot reproduce this error, please make sure you are using the latest version of pytroch-transformers
