### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'max_ndocs_in_batch'

### ISSUE THREAD

**Issue by chandanrao007** [nlpyang/PreSumm#137]
While training I am getting this error. I am using the dev branch code.

[2020-03-28 15:49:15,981 INFO] * number of parameters: 75951418
[2020-03-28 15:49:15,981 INFO] Start training...
[2020-03-28 15:49:16,218 INFO] Loading train dataset from bert_data_cnndm_final/cnndm.train.18.bert.pt, number of examples: 1998
Traceback (most recent call last):
  File "src/train.py", line 122, in <module>
    train_abs(args, device_id)
  File "/content/PreSumm/src/train_abstractive.py", line 273, in train_abs
    train_abs_single(args, device_id)
  File "/content/PreSumm/src/train_abstractive.py", line 334, in train_abs_single
    trainer.train(train_iter_fct, args.train_steps)
  File "/content/PreSumm/src/models/trainer.py", line 142, in train
    for i, batch in enumerate(train_iter):
  File "/content/PreSumm/src/models/data_loader.py", line 144, in __iter__
    for batch in self.cur_iter:
  File "/content/PreSumm/src/models/data_loader.py", line 280, in __iter__
    for idx, minibatch in enumerate(self.batches):
  File "/content/PreSumm/src/models/data_loader.py", line 258, in create_batches
    for buffer in self.batch_buffer(data, self.batch_size * 300):
  File "/content/PreSumm/src/models/data_loader.py", line 230, in batch_buffer
    size_so_far = self.batch_size_fn(ex, len(minibatch), self.args.max_ndocs_in_batch)
AttributeError: 'Namespace' object has no attribute 'max_ndocs_in_batch'

**Comment by chandanrao007** [comment]
Sorry I got it.

**Comment by onrmrt** [comment]
Add "-" prefix to "max_ndocs_in_batch". (-max_ndocs_in_batch)

**Comment by nlpyang** [comment]
Please use master version for regular training, dev branch should be only used for -mode test_text .

**Comment by chandanrao007** [comment]
Ok, Thanks..
