### ISSUE TITLE
TypeError: forward() got multiple values for argument 'attention_mask'

### ISSUE THREAD

**Issue by seanswyi** [nlpyang/PreSumm#139]
Hello. I'm trying to run the code but am facing some difficulties. I'm assuming that this may be because of a version mismatch, but I wanted to be sure.

When I run the code with:

```Python
python ./train.py -task abs -mode train -bert_data_path ../bert_data/cnndm -dec_dropout 0.2 -model_path MODEL_PATH -sep_optim true -lr_bert 0.002 -lr_dec 0.2 -save_checkpoint_steps 2000 -batch_size 140 -train_steps 200000 -report_every 50 -accum_count 5 -use_bert_emb true -use_interval true -warmup_steps_bert 20000 -warmup_steps_dec 10000 -max_pos 512 -visible_gpus -1 -log_file ../logs/abs_bert_cnndm
```

I get the error:

```Python
[2020-03-28 15:03:43,228 INFO] Loading train dataset from ../bert_data/cnndm.train.123.bert.pt, number of examples: 2001
Traceback (most recent call last):
  File "./train.py", line 122, in <module>
    train_abs(args, device_id)
  File "/home/user1/PreSumm/src/train_abstractive.py", line 273, in train_abs
    train_abs_single(args, device_id)
  File "/home/user1/PreSumm/src/train_abstractive.py", line 334, in train_abs_single
    trainer.train(train_iter_fct, args.train_steps)
  File "/home/user1/PreSumm/src/models/trainer.py", line 158, in train
    report_stats)
  File "/home/user1/PreSumm/src/models/trainer.py", line 223, in _gradient_accumulation
    outputs, scores = self.model(src, tgt,segs, clss, mask_src, mask_tgt, mask_cls)
  File "/home/user1/anaconda3/envs/seanconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user1/PreSumm/src/models/model_builder.py", line 241, in forward
    top_vec = self.bert(src, segs, mask_src)
  File "/home/user1/anaconda3/envs/userconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user1/PreSumm/src/models/model_builder.py", line 127, in forward
    top_vec, _ = self.model(x, segs, attention_mask=mask)
  File "/home/user1/anaconda3/envs/userconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got multiple values for argument 'attention_mask'
```

What's wrong here? Any ideas on how to fix the code?

**Comment by 6desislava6** [comment]
You are having the same problem as this person [here](https://github.com/nlpyang/PreSumm/issues/84). The solutions works (I just bumped into the same problem).

**Comment by seanswyi** [comment]
Thanks!
