### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGUSR1'. (Specific to Windows Machine)

### ISSUE THREAD

**Issue by AanchalA** [nlpyang/PreSumm#149]
When I try to run the command for extractive training, I get the following error. This error is specific to a windows machine. Can someone help me with a work-around.

Traceback (most recent call last):
  File "train.py", line 146, in <module>
    train_ext(args, device_id)
  File "F:\Data Science\NLP\BERT\PreSumm\src\train_extractive.py", line 201, in train_ext
    train_multi_ext(args)
  File "F:\Data Science\NLP\BERT\PreSumm\src\train_extractive.py", line 35, in train_multi_ext
    error_handler = ErrorHandler(error_queue)
  File "F:\Data Science\NLP\BERT\PreSumm\src\train_extractive.py", line 83, in __init__
    signal.signal(signal.SIGUSR1, self.signal_handler)
AttributeError: module 'signal' has no attribute 'SIGUSR1'

**Comment by teejay13** [comment]
Hello @AanchalA did you find the solution to this error
thanks
