### ISSUE TITLE
error in step 3 

### ISSUE THREAD

**Issue by Marwan1137** [nlpyang/PreSumm#248]
(test) PS C:\Users\marwa\Downloads\Compressed\PreSumm-master\src> python preprocess.py -mode tokenize -raw_path "C:\Users\marwa\Downloads\Compressed\PreSumm-master\cnn\stories" -save_path "C:\Users\marwa\Downloads\Compressed\PreSumm-master\merged stories"
Preparing to tokenize C:\Users\marwa\Downloads\Compressed\PreSumm-master\cnn\stories to C:\Users\marwa\Downloads\Compressed\PreSumm-master\merged stories...
Making list of files to tokenize...
Tokenizing 304356 files in C:\Users\marwa\Downloads\Compressed\PreSumm-master\cnn\stories and saving in C:\Users\marwa\Downloads\Compressed\PreSumm-master\merged stories...
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP
Stanford CoreNLP Tokenizer has finished.
Traceback (most recent call last):
  File "preprocess.py", line 73, in <module>
    eval('data_builder.'+args.mode + '(args)')
  File "<string>", line 1, in <module>
  File "C:\Users\marwa\Downloads\Compressed\PreSumm-master\src\prepro\data_builder.py", line 137, in tokenize
    tokenized_stories_dir, num_tokenized, stories_dir, num_orig))
Exception: The tokenized stories directory C:\Users\marwa\Downloads\Compressed\PreSumm-master\merged stories contains 0 files, but it should contain the same number as C:\Users\marwa\Downloads\Compressed\PreSumm-master\cnn\stories (which has 304356 files). Was there an error during tokenization?

**Comment by WSChange** [comment]
check you library.use the same library as the author's use
