### ISSUE TITLE
ValueError: too many values to unpack (expected 5)

### ISSUE THREAD

**Issue by Simons2017** [nlpyang/PreSumm#29]
Hello, when I set mode to validate or test, I encountered the following problem. Do you have a good solution? Thank you！@nlpyang 
[2019-09-16 17:03:34,533 INFO] loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-pytorch_model.bin from cache at ../../temp/aa1ef1aede4482d0dbcd4d52baad8ae300e60902e88fcb0bebdec09afd232066.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
[2019-09-16 17:03:37,976 INFO] Loading test dataset from cnndm/cnndm.test.0.bert.pt, number of examples: 2001
[2019-09-16 17:03:51,366 INFO] loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at ../../temp/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    validate_abs(args, device_id)
  File "/home/cai/yym/ddl/final/PreSumm-master/train_abstractive.py", line 155, in validate_abs
    test_abs(args, device_id, cp, step)
  File "/home/cai/yym/ddl/final/PreSumm-master/train_abstractive.py", line 225, in test_abs
    predictor.translate(test_iter, step)
  File "/home/cai/yym/ddl/final/PreSumm-master/models/predictor.py", line 153, in translate
    translations = self.from_batch(batch_data)
  File "/home/cai/yym/ddl/final/PreSumm-master/models/predictor.py", line 106, in from_batch
    batch.tgt_str, batch.src))
ValueError: too many values to unpack (expected 5)

**Comment by nlpyang** [comment]
please paste your command here

**Comment by Simons2017** [comment]
> please paste your command here

python train.py -task abs -mode validate -batch_size 3000 -test_batch_size 500 -bert_data_path cnndm/cnndm -log_file logs/val_abs_bert_cnndm -model_path model_abs -sep_optim true -use_interval true -visible_gpus 0 -max_pos 512 -max_length 200 -alpha 0.95 -min_length 50 -result_path logs/abs_bert_cnndm

**Comment by nlpyang** [comment]
I think you need to pull the code again.
This has already been fixed in https://github.com/nlpyang/PreSumm/commit/fa69433dffa61e3dffc13bc299f7f949fcf305da
