### ISSUE TITLE
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported

### ISSUE THREAD

**Issue by juliahane** [nlpyang/PreSumm#54]
Hi
I am getting this error while running with the default dataset provided in the github page and default command, I have a deadline approaching very soon and appreciate  your help.
thanks

Traceback (most recent call last):
  File "train.py", line 122, in <module>
    train_abs(args, device_id)
  File "/remote/user/dev/PreSumm/src/train_abstractive.py", line 276, in train_abs
    train_abs_single(args, device_id)
  File "/remote/user/dev/PreSumm/src/train_abstractive.py", line 339, in train_abs_single
    trainer.train(train_iter_fct, args.train_steps)
  File "/remote/user/dev/PreSumm/src/models/trainer.py", line 142, in train
    for i, batch in enumerate(train_iter):
  File /remote/user/dev/PreSumm/src/models/data_loader.py", line 143, in __iter__
    for batch in self.cur_iter:
  File "/remote/user/dev/PreSumm/src/models/data_loader.py", line 285, in __iter__
    batch = Batch(minibatch, self.device, self.is_test)
  File "/remote/user/dev/PreSumm/src/models/data_loader.py", line 33, in __init__
    mask_src = 1 - (src == 0)
  File "/remote/user/dev/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/torch/tensor.py", line 325, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.

**Comment by nlpyang** [comment]
Please use torch==1.1.0

**Comment by Martha-91** [comment]
@ghost 
torch version 1.1.0 isnot available now.
So I updated this code 
mask_src = 1 - (src == 0)
to 
mask_src = 1 - (src.float() == 0).float()
