### ISSUE TITLE
Before training i got some question

### ISSUE THREAD

**Issue by zz860808** [nlpyang/PreSumm#84]
Hi, thanks for your work here. i got an error after i do the command.
__`python train.py  -task abs -mode train -bert_data_path ../bert_data/cnndm -dec_dropout 0.2  -model_path ../MODEL -sep_optim true -lr_bert 0.002 -lr_dec 0.2 -save_checkpoint_steps 2000 -batch_size 140 -train_steps 200000 -report_every 50 -accum_count 5 -use_bert_emb true -use_interval true -warmup_steps_bert 20000 -warmup_steps_dec 10000 -max_pos 512 -visible_gpus 0  -log_file ../logs/abs_bert_`__

After doing that i got these error messege if there's any can help me? thanks so much!
```

Traceback (most recent call last):
  File "train.py", line 122, in <module>
    train_abs(args, device_id)
  File "/home/ubuntu/will/PreSumm-master/src/train_abstractive.py", line 273, in train_abs
    train_abs_single(args, device_id)
  File "/home/ubuntu/will/PreSumm-master/src/train_abstractive.py", line 334, in train_abs_single
    trainer.train(train_iter_fct, args.train_steps)
  File "/home/ubuntu/will/PreSumm-master/src/models/trainer.py", line 158, in train
    report_stats)
  File "/home/ubuntu/will/PreSumm-master/src/models/trainer.py", line 223, in _gradient_accumulation
    outputs, scores = self.model(src, tgt,segs, clss, mask_src, mask_tgt, mask_cls)
  File "/home/ubuntu/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/will/PreSumm-master/src/models/model_builder.py", line 241, in forward
    top_vec = self.bert(src, segs, mask_src)
  File "/home/ubuntu/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/will/PreSumm-master/src/models/model_builder.py", line 127, in forward
    top_vec, _ = self.model(x, segs, attention_mask=mask)
  File "/home/ubuntu/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got multiple values for argument 'attention_mask'
```

**Comment by yuta-hitomi** [comment]
I think that you don't use pytorch-transformers but use transformers.
If that is correct, you should check https://github.com/huggingface/transformers .
And read `Migrating from pytorch-transformers to transformers` .
