### ISSUE TITLE
loading state_dict for AbsSummarizer

### ISSUE THREAD

**Issue by kurodenjiro** [nlpyang/PreSumm#87]
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    test_abs(args, device_id, cp, step)
  File "E:\project\PreSumm\src\train_abstractive.py", line 215, in test_abs
    model = AbsSummarizer(args, device, checkpoint)
  File "E:\project\PreSumm\src\models\model_builder.py", line 217, in __init__
    self.load_state_dict(checkpoint['model'], strict=True)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for AbsSummarizer:
        Missing key(s) in state_dict: "decoder.embeddings.weight", "decoder.pos_emb.pe", "decoder.transformer_layers.0.mask", "decoder.transformer_layers.0.self_attn.linear_keys.weight", "decoder.transformer_layers.0.self_attn.linear_keys.bias", "decoder.transformer_layers.0.self_attn.linear_values.weight", "decoder.transformer_layers.0.self_attn.linear_values.bias", "decoder.transformer_layers.0.self_attn.linear_query.weight", "decoder.transformer_layers.0.self_attn.linear_query.bias", "decoder.transformer_layers.0.self_attn.final_linear.weight", "decoder.transformer_layers.0.self_attn.final_linear.bias", "decoder.transformer_layers.0.context_attn.linear_keys.weight", "decoder.transformer_layers.0.context_attn.linear_keys.bias", "decoder.transformer_layers.0.context_attn.linear_values.weight", "decoder.transformer_layers.0.context_attn.linear_values.bias", "decoder.transformer_layers.0.context_attn.linear_query.weight", "decoder.transformer_layers.0.context_attn.linear_query.bias", "decoder.transformer_layers.0.context_attn.final_linear.weight", "decoder.transformer_layers.0.context_attn.final_linear.bias", "decoder.transformer_layers.0.feed_forward.w_1.weight", "decoder.transformer_layers.0.feed_forward.w_1.bias", "decoder.transformer_layers.0.feed_forward.w_2.weight", "decoder.transformer_layers.0.feed_forward.w_2.bias", "decoder.transformer_layers.0.feed_forward.layer_norm.weight", "decoder.transformer_layers.0.feed_forward.layer_norm.bias", "decoder.transformer_layers.0.layer_norm_1.weight", "decoder.transformer_layers.0.layer_norm_1.bias", "decoder.transformer_layers.0.layer_norm_2.weight", "decoder.transformer_layers.0.layer_norm_2.bias", "decoder.transformer_layers.1.mask", "decoder.transformer_layers.1.self_attn.linear_keys.weight", "decoder.transformer_layers.1.self_attn.linear_keys.bias", "decoder.transformer_layers.1.self_attn.linear_values.weight", "decoder.transformer_layers.1.self_attn.linear_values.bias", "decoder.transformer_layers.1.self_attn.linear_query.weight", "decoder.transformer_layers.1.self_attn.linear_query.bias", "decoder.transformer_layers.1.self_attn.final_linear.weight", "decoder.transformer_layers.1.self_attn.final_linear.bias", "decoder.transformer_layers.1.context_attn.linear_keys.weight", "decoder.transformer_layers.1.context_attn.linear_keys.bias", "decoder.transformer_layers.1.context_attn.linear_values.weight", "decoder.transformer_layers.1.context_attn.linear_values.bias", "decoder.transformer_layers.1.context_attn.linear_query.weight", "decoder.transformer_layers.1.context_attn.linear_query.bias", "decoder.transformer_layers.1.context_attn.final_linear.weight", "decoder.transformer_layers.1.context_attn.final_linear.bias", "decoder.transformer_layers.1.feed_forward.w_1.weight", "decoder.transformer_layers.1.feed_forward.w_1.bias", "decoder.transformer_layers.1.feed_forward.w_2.weight", "decoder.transformer_layers.1.feed_forward.w_2.bias", "decoder.transformer_layers.1.feed_forward.layer_norm.weight", "decoder.transformer_layers.1.feed_forward.layer_norm.bias", "decoder.transformer_layers.1.layer_norm_1.weight", "decoder.transformer_layers.1.layer_norm_1.bias", "decoder.transformer_layers.1.layer_norm_2.weight", "decoder.transformer_layers.1.layer_norm_2.bias", "decoder.transformer_layers.2.mask", "decoder.transformer_layers.2.self_attn.linear_keys.weight", "decoder.transformer_layers.2.self_attn.linear_keys.bias", "decoder.transformer_layers.2.self_attn.linear_values.weight", "decoder.transformer_layers.2.self_attn.linear_values.bias", "decoder.transformer_layers.2.self_attn.linear_query.weight", "decoder.transformer_layers.2.self_attn.linear_query.bias", "decoder.transformer_layers.2.self_attn.final_linear.weight", "decoder.transformer_layers.2.self_attn.final_linear.bias", "decoder.transformer_layers.2.context_attn.linear_keys.weight", "decoder.transformer_layers.2.context_attn.linear_keys.bias", "decoder.transformer_layers.2.context_attn.linear_values.weight", "decoder.transformer_layers.2.context_attn.linear_values.bias", "decoder.transformer_layers.2.context_attn.linear_query.weight", "decoder.transformer_layers.2.context_attn.linear_query.bias", "decoder.transformer_layers.2.context_attn.final_linear.weight", "decoder.transformer_layers.2.context_attn.final_linear.bias", "decoder.transformer_layers.2.feed_forward.w_1.weight", "decoder.transformer_layers.2.feed_forward.w_1.bias", "decoder.transformer_layers.2.feed_forward.w_2.weight", "decoder.transformer_layers.2.feed_forward.w_2.bias", "decoder.transformer_layers.2.feed_forward.layer_norm.weight", "decoder.transformer_layers.2.feed_forward.layer_norm.bias", "decoder.transformer_layers.2.layer_norm_1.weight", "decoder.transformer_layers.2.layer_norm_1.bias", "decoder.transformer_layers.2.layer_norm_2.weight", "decoder.transformer_layers.2.layer_norm_2.bias", "decoder.transformer_layers.3.mask", "decoder.transformer_layers.3.self_attn.linear_keys.weight", "decoder.transformer_layers.3.self_attn.linear_keys.bias", "decoder.transformer_layers.3.self_attn.linear_values.weight", "decoder.transformer_layers.3.self_attn.linear_values.bias", "decoder.transformer_layers.3.self_attn.linear_query.weight", "decoder.transformer_layers.3.self_attn.linear_query.bias", "decoder.transformer_layers.3.self_attn.final_linear.weight", "decoder.transformer_layers.3.self_attn.final_linear.bias", "decoder.transformer_layers.3.context_attn.linear_keys.weight", "decoder.transformer_layers.3.context_attn.linear_keys.bias", "decoder.transformer_layers.3.context_attn.linear_values.weight", "decoder.transformer_layers.3.context_attn.linear_values.bias", "decoder.transformer_layers.3.context_attn.linear_query.weight", "decoder.transformer_layers.3.context_attn.linear_query.bias", "decoder.transformer_layers.3.context_attn.final_linear.weight", "decoder.transformer_layers.3.context_attn.final_linear.bias", "decoder.transformer_layers.3.feed_forward.w_1.weight", "decoder.transformer_layers.3.feed_forward.w_1.bias", "decoder.transformer_layers.3.feed_forward.w_2.weight", "decoder.transformer_layers.3.feed_forward.w_2.bias", "decoder.transformer_layers.3.feed_forward.layer_norm.weight", "decoder.transformer_layers.3.feed_forward.layer_norm.bias", "decoder.transformer_layers.3.layer_norm_1.weight", "decoder.transformer_layers.3.layer_norm_1.bias", "decoder.transformer_layers.3.layer_norm_2.weight", "decoder.transformer_layers.3.layer_norm_2.bias", "decoder.transformer_layers.4.mask", "decoder.transformer_layers.4.self_attn.linear_keys.weight", "decoder.transformer_layers.4.self_attn.linear_keys.bias", "decoder.transformer_layers.4.self_attn.linear_values.weight", "decoder.transformer_layers.4.self_attn.linear_values.bias", "decoder.transformer_layers.4.self_attn.linear_query.weight", "decoder.transformer_layers.4.self_attn.linear_query.bias", "decoder.transformer_layers.4.self_attn.final_linear.weight", "decoder.transformer_layers.4.self_attn.final_linear.bias", "decoder.transformer_layers.4.context_attn.linear_keys.weight", "decoder.transformer_layers.4.context_attn.linear_keys.bias", "decoder.transformer_layers.4.context_attn.linear_values.weight", "decoder.transformer_layers.4.context_attn.linear_values.bias", "decoder.transformer_layers.4.context_attn.linear_query.weight", "decoder.transformer_layers.4.context_attn.linear_query.bias", "decoder.transformer_layers.4.context_attn.final_linear.weight", "decoder.transformer_layers.4.context_attn.final_linear.bias", "decoder.transformer_layers.4.feed_forward.w_1.weight", "decoder.transformer_layers.4.feed_forward.w_1.bias", "decoder.transformer_layers.4.feed_forward.w_2.weight", "decoder.transformer_layers.4.feed_forward.w_2.bias", "decoder.transformer_layers.4.feed_forward.layer_norm.weight", "decoder.transformer_layers.4.feed_forward.layer_norm.bias", "decoder.transformer_layers.4.layer_norm_1.weight", "decoder.transformer_layers.4.layer_norm_1.bias", "decoder.transformer_layers.4.layer_norm_2.weight", "decoder.transformer_layers.4.layer_norm_2.bias", "decoder.transformer_layers.5.mask", "decoder.transformer_layers.5.self_attn.linear_keys.weight", "decoder.transformer_layers.5.self_attn.linear_keys.bias", "decoder.transformer_layers.5.self_attn.linear_values.weight", "decoder.transformer_layers.5.self_attn.linear_values.bias", "decoder.transformer_layers.5.self_attn.linear_query.weight", "decoder.transformer_layers.5.self_attn.linear_query.bias", "decoder.transformer_layers.5.self_attn.final_linear.weight", "decoder.transformer_layers.5.self_attn.final_linear.bias", "decoder.transformer_layers.5.context_attn.linear_keys.weight", "decoder.transformer_layers.5.context_attn.linear_keys.bias", "decoder.transformer_layers.5.context_attn.linear_values.weight", "decoder.transformer_layers.5.context_attn.linear_values.bias", "decoder.transformer_layers.5.context_attn.linear_query.weight", "decoder.transformer_layers.5.context_attn.linear_query.bias", "decoder.transformer_layers.5.context_attn.final_linear.weight", "decoder.transformer_layers.5.context_attn.final_linear.bias", "decoder.transformer_layers.5.feed_forward.w_1.weight", "decoder.transformer_layers.5.feed_forward.w_1.bias", "decoder.transformer_layers.5.feed_forward.w_2.weight", "decoder.transformer_layers.5.feed_forward.w_2.bias", "decoder.transformer_layers.5.feed_forward.layer_norm.weight", "decoder.transformer_layers.5.feed_forward.layer_norm.bias", "decoder.transformer_layers.5.layer_norm_1.weight", "decoder.transformer_layers.5.layer_norm_1.bias", "decoder.transformer_layers.5.layer_norm_2.weight", "decoder.transformer_layers.5.layer_norm_2.bias", "decoder.layer_norm.weight", "decoder.layer_norm.bias", "generator.0.weight", "generator.0.bias".
        Unexpected key(s) in state_dict: "ext_layer.pos_emb.pe", "ext_layer.transformer_inter.0.self_attn.linear_keys.weight", "ext_layer.transformer_inter.0.self_attn.linear_keys.bias", "ext_layer.transformer_inter.0.self_attn.linear_values.weight", "ext_layer.transformer_inter.0.self_attn.linear_values.bias", "ext_layer.transformer_inter.0.self_attn.linear_query.weight", "ext_layer.transformer_inter.0.self_attn.linear_query.bias", "ext_layer.transformer_inter.0.self_attn.final_linear.weight", "ext_layer.transformer_inter.0.self_attn.final_linear.bias", "ext_layer.transformer_inter.0.feed_forward.w_1.weight", "ext_layer.transformer_inter.0.feed_forward.w_1.bias", "ext_layer.transformer_inter.0.feed_forward.w_2.weight", "ext_layer.transformer_inter.0.feed_forward.w_2.bias", "ext_layer.transformer_inter.0.feed_forward.layer_norm.weight", "ext_layer.transformer_inter.0.feed_forward.layer_norm.bias", "ext_layer.transformer_inter.0.layer_norm.weight", "ext_layer.transformer_inter.0.layer_norm.bias", "ext_layer.transformer_inter.1.self_attn.linear_keys.weight", "ext_layer.transformer_inter.1.self_attn.linear_keys.bias", "ext_layer.transformer_inter.1.self_attn.linear_values.weight", "ext_layer.transformer_inter.1.self_attn.linear_values.bias", "ext_layer.transformer_inter.1.self_attn.linear_query.weight", "ext_layer.transformer_inter.1.self_attn.linear_query.bias", "ext_layer.transformer_inter.1.self_attn.final_linear.weight", "ext_layer.transformer_inter.1.self_attn.final_linear.bias", "ext_layer.transformer_inter.1.feed_forward.w_1.weight", "ext_layer.transformer_inter.1.feed_forward.w_1.bias", "ext_layer.transformer_inter.1.feed_forward.w_2.weight", "ext_layer.transformer_inter.1.feed_forward.w_2.bias", "ext_layer.transformer_inter.1.feed_forward.layer_norm.weight", "ext_layer.transformer_inter.1.feed_forward.layer_norm.bias", "ext_layer.transformer_inter.1.layer_norm.weight", "ext_layer.transformer_inter.1.layer_norm.bias", "ext_layer.layer_norm.weight", "ext_layer.layer_norm.bias", "ext_layer.wo.weight", "ext_layer.wo.bias".

**Comment by nlpyang** [comment]
please use -task abs for abstractive summarization
